version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
    networks:
      - kafka_services

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    networks:
      - kafka_services
    depends_on:
      - zookeeper
  
  leak-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - kafka_services
    ports:
      - '6060:6060'

networks:
  kafka_services: {}